In [1]:
import numpy as np

In [2]:
# Creating Array from list 
arr = np.array([1,2,3])

    # using functions
arr_zero = np.zeros((3,2)) 
arr_ones = np.ones((4,5)) 
arr_arange = np.arange(0,10,2)

In [3]:
print(arr)
print(arr_zero)
print(arr_ones)
print(arr_arange)

[1 2 3]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 2 4 6 8]


In [4]:
# array operations
    # element wise operation
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b

    # broadcasting
d = np.array([10])
print(c)
print(d+a)

[5 7 9]
[11 12 13]


In [5]:
# indexing and slicing
arr_1 = np.array([10,20,30,40])
    # basic indexing
print(arr_1[0])
print(arr_1[-1])

    # slicing 
print(arr_1[1:3])

    # multi-dimensional indexing
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2[:2,2])

10
40
[20 30]
[3 6]


In [43]:
# reshaping arrays
arr_3 = np.array([[1,2,3],[4,5,6]])
    # Reshape
reshaped = np.reshape(arr_3, [3,2])
    # Flatten
flat = arr_3.flatten()
print(reshaped)
print(flat)

# or

arr_flat = arr_3.flat
for i in arr_flat:
    print(i)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
1
2
3
4
5
6


In [45]:
print(reshaped)
print(flat)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [47]:
# Aggression function
    # sum, mean, max
arr_4 = np.array([1, 2, 3, 4])
total = arr_4.sum()
maximum = arr_4.max()
minimum = arr_4.min()

    # axis-wise operations
arr_5 = np.array([[1,3,5],[7,9,11]])
col_sum = arr_5.sum(axis = 0)
row_sum = arr_5.sum(axis = 1)

In [49]:
print(total)
print(maximum)
print(minimum)

print(col_sum)
print(row_sum)

10
4
1
[ 8 12 16]
[ 9 27]


In [51]:
# linear algebra
    # dot product
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

dot_product = np.dot(x,y)
print(dot_product)

    # transpose
arr_6 = np.array([[1,2,3],[4,5,6]])
print(arr_6)
transposed = arr_6.T
print(transposed)

    # inverse
    # imp -> matrix is square and has a non-zero determinant
arr_7 = np.array([[10,20],[30,40]])
inv = np.linalg.inv(arr_7)
print(inv)

[[19 22]
 [43 50]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[-0.2   0.1 ]
 [ 0.15 -0.05]]


In [53]:
# Random number generation
    # random number
rand_arr = np.random.rand(3,3) # 3x3 matrix of random numbers
rand_int = np.random.randint(0,10, size = (3,3))  # 3x3 matrix of random integers between 0 and 10
print(rand_arr)
print(rand_int)

    # shuffling
arr_8 = np.array([1,2,3,4,5])
np.random.shuffle(arr_8)
print(arr_8)

[[0.55166587 0.63824731 0.56079865]
 [0.83292471 0.77790055 0.81278618]
 [0.02954123 0.92638445 0.90777249]]
[[3 8 9]
 [1 8 7]
 [7 6 1]]
[4 5 2 3 1]


In [55]:
arr_7 = np.arange(15)
print(arr_7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [57]:
lspace_arr = np.linspace(1,5,10)
print(lspace_arr)   # will provide a list of equal diff b/w 1 and 5 and total 10 elements

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [63]:
arr_7.nbytes

120

In [95]:
# argmax    ]
# argmin    ]  provide the index of the specific things
# argsort   ]
arr = np.array([5,3,5,6,9,0])
print(arr.argmax())
print(arr.argmin())
print(arr.argsort())

4
5
[5 1 0 2 3 4]


In [97]:
np.where(arr>4)

(array([0, 2, 3, 4]),)

In [99]:
np.count_nonzero(arr)

5

In [101]:
np.nonzero(arr)

(array([0, 1, 2, 3, 4]),)

In [103]:
import sys

In [127]:
py_arr = [4,3,66,3,2]
np_arr = np.array(py_arr)
print("Size of numpy array : ", np_arr.itemsize * np_arr.size)
print("Size of python array : ", sys.getsizeof(1) * len(py_arr))

Size of numpy array :  40
Size of python array :  140
