In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
!pip install word2number
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience.fillna('zero', inplace=True)

/var/folders/dg/cvz8h7590n1248mdbg0b0xxr0000gn/T/ipykernel_11220/1197290021.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.experience.fillna('zero', inplace=True)


In [8]:
df['experience'] = df['experience'].apply(w2n.word_to_num) 
type(df['experience'])

pandas.core.series.Series

Single Brackets *df['experience']*: You get a Series. This is a more compact form, useful for operations that don't require the 2D structure of a DataFrame. Series can be thought of as a single column of data.

Double Brackets *df[['experience']]*: You get a DataFrame, which is a 2D structure, even if it contains only one column. This is useful when you want to retain the DataFrame format for consistency, especially if you're going to select multiple columns or need to pass the result into functions expecting a DataFrame.

In [10]:
df.test_score(out_of_10)

AttributeError: 'DataFrame' object has no attribute 'test_score'

In [12]:
test_median = df['test_score(out of 10)'].median()

In [13]:
df['test_score(out of 10)'].fillna(test_median, inplace=True)

/var/folders/dg/cvz8h7590n1248mdbg0b0xxr0000gn/T/ipykernel_11220/2666078899.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['test_score(out of 10)'].fillna(test_median, inplace=True)


In [14]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [18]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [19]:
reg.intercept_

17737.263464337688

In [20]:
reg.predict([[2, 9, 6]])

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [22]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.263464337688

53205.96797671769

In [23]:
reg.predict([[12, 10, 10]])

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [24]:
2812.95487627*12 + 1845.70596798*10 + 2205.24017467*10 + 17737.263464337688

92002.18340607767