In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [16]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
# data preprocessing
df.bedrooms.median()

4.0

In [20]:
df.fillna(4.0, inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

price = m1*area + m2*bedrooms + m3*age + b
price -> dependent var
area, bedrooms, age -> independent var
3 coefficients and 1 intercept

In [22]:

reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [23]:
reg.intercept_

221323.00186540402

In [24]:
reg.predict([[3000,3,40]])

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [27]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 +221323.00186540402

498408.25157402403

In [25]:
reg.predict([[2500,4,5]])

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [28]:
112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 +221323.00186540402

578876.037484014