In [1]:
import tensorflow as tf

In [2]:
# 1-D , 2-D , 3-D , 4-D tensors

# tf.constant(
#     value, dtype=None, shape=None, name=&#x27;Const'
# ) -> Union[tf.Operation, ops._EagerTensorBase]

tensor_one_d = tf.constant([1,2,3], dtype = tf.int32)  # shape -> (3,)
print(tensor_one_d)

tensor_two_d = tf.constant([[2,3,4],[5,6,7]], dtype = tf.float32)   # shape -> (2,3)
print(tensor_two_d)

tensor_three_d = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]],
], dtype = tf.int64)    # shape -> (3,2,2)
print(tensor_three_d)

tensor_four_d = tf.constant([    
[[[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]],
[[[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]],
[[[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]],
], dtype = tf.int32)    # shape -> (3,3,2,2)
print(tensor_four_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[2. 3. 4.]
 [5. 6. 7.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int64)
tf.Tensor(
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]], shape=(3, 3, 2, 2), dtype=int32)


In [3]:
tf.constant(0, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [4]:
tf.constant([1,2,3,4,5,6], shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [5]:
print(tensor_one_d.shape)
print(tensor_three_d.ndim)

(3,)
3


tensor_2 = tf.constant([[1,2,3],[4,5.,6]], dtype = int32)
This shows an error we cant directly assign floating constant int type --> we use casting ->

In [6]:
# so for above problem we would use casting method
# tf.cast(
#     x, dtype, name=None
# )
tensor_3 = tf.constant([1,2,0,4.,5])
casted_tensor_3 = tf.cast(tensor_3, dtype = tf.int64)
casted_tensor_3_1 = tf.cast(tensor_3,dtype = tf.bool)
print(tensor_3)
print(casted_tensor_3)
print(casted_tensor_3_1)

tf.Tensor([1. 2. 0. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([1 2 0 4 5], shape=(5,), dtype=int64)
tf.Tensor([ True  True False  True  True], shape=(5,), dtype=bool)


In [7]:
import numpy as np

In [8]:
np_arr = np.array([1,2,3])
print(np_arr)

[1 2 3]


In [9]:
converted_tensor = tf.convert_to_tensor(np_arr)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [10]:
# Construct an identity matrix, or a batch of matrices.

# tf.eye(    
#     num_rows,
#     num_columns=None,
#     batch_shape=None,
#     dtype=tf.dtypes.float32,
#     name=None
# )
identity_tensor = tf.eye(
    4,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.int32,
    name=None
)
print(identity_tensor)
print(4 * identity_tensor)

tf.Tensor(
[[[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  [0 0 0 1]]], shape=(3, 4, 4), dtype=int32)
tf.Tensor(
[[[4 0 0 0]
  [0 4 0 0]
  [0 0 4 0]
  [0 0 0 4]]

 [[4 0 0 0]
  [0 4 0 0]
  [0 0 4 0]
  [0 0 0 4]]

 [[4 0 0 0]
  [0 4 0 0]
  [0 0 4 0]
  [0 0 0 4]]], shape=(3, 4, 4), dtype=int32)


In [11]:
# tf.fill(
#     dims, value, name=None, layout=None
# )

fill_tensor = tf.fill([3,4], 2, name=None)
print(fill_tensor)

tf.Tensor(
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]], shape=(3, 4), dtype=int32)


In [12]:
# tf.ones(
#     shape,
#     dtype=tf.dtypes.float32,
#     name=None,
#     layout=None
# )
tf.ones(
    [3,3],
    dtype=tf.dtypes.int32,
    name = None
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [13]:
# tf.ones_like(
#     input, dtype=None, name=None, layout=None
# )
one_like_tensor = tf.constant([[1,2],[3,4]])
tf.ones_like(one_like_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [14]:
# tf.zeros(
#     shape,
#     dtype=tf.dtypes.float32,
#     name=None,
#     layout=None
# )
zero_tensor = tf.zeros([2,3], dtype=tf.dtypes.int32)
print(zero_tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [15]:
# tf.zeros_like(
#     input, dtype=None, name=None, layout=None
# )

zero_like_tensor = tf.zeros_like([[4,5,6],[2,4,6],[8,6,5]], dtype=tf.dtypes.int32)
print(zero_like_tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [16]:
tf.shape(zero_like_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [17]:
zero_tensor.shape

TensorShape([2, 3])

In [18]:
# tf.rank(
#     input, name=None
# )
tensor_5 = tf.constant([
    [[1,2,3],[3,3,4]],
    [[8,6,8],[5,6,5]],
    [[4,5,4],[0,0,0]],
])
print(tf.rank(tensor_5))

tf.Tensor(3, shape=(), dtype=int32)


In [19]:
# tf.size(
#     input, out_type=None, name=None
# )
tf.size(tensor_5, out_type=tf.dtypes.bool)  # in which datatype you want the output of size to be in ...

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [20]:
tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.4502918 ,  0.20406288],
       [-1.6817725 , -0.9881382 ],
       [ 0.2972523 , -0.70697296]], dtype=float32)>

In [21]:
tf.random.uniform(
    [4,4],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.9995028 , 0.6449897 , 0.8670044 , 0.01612949],
       [0.3193934 , 0.6445205 , 0.5227653 , 0.5001308 ],
       [0.22915602, 0.7144408 , 0.91913486, 0.9966564 ],
       [0.8947203 , 0.15357864, 0.01683235, 0.20793426]], dtype=float32)>

In [22]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))

tf.Tensor([9 3 6], shape=(3,), dtype=int32)
tf.Tensor([9 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [23]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=10, dtype=tf.dtypes.int32, seed=10))

tf.Tensor([9 3 6], shape=(3,), dtype=int32)
tf.Tensor([9 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [24]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [25]:
tensor_index = tf.constant([
    [[1,2,3],[3,3,4]],  # 0
    [[8,6,8],[5,6,5]],  # 1
    [[4,5,4],[0,0,0]],  # 2
])
# index(minindex:maxindex+1:step, minindex:maxindex+1:step, minindex:maxindex+1:step)
print(tensor_index[1:, 0, :2]) # o/p -> [8,6],[4,5]

tf.Tensor(
[[8 6]
 [4 5]], shape=(2, 2), dtype=int32)


In [26]:
tensor_9 = tf.constant([[1,2,0],
                        [3,5,-1],
                        [1,5,6],
                        [2,3,8]])     # o/p -> [1,2],[3,5],[1,5]
print(tensor_9[:3,:2])
print(tensor_9[...,1]) # same as [:,1]

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [27]:
# Math function of tensorflow
    # abs(x) ->  if x<0  or x>0 then abs(x) == |x|
tf.math.abs(
    -3, name=None
)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [28]:
# add function for both numbers and matrices
a = tf.constant([1,2,3,5,6])
b = tf.constant([8])
b_stretched = tf.constant([8,8,8,8,8])
print(a+b)
print(tf.math.add(a,b))
print(tf.math.add(a,b_stretched))

tf.Tensor([ 9 10 11 13 14], shape=(5,), dtype=int32)
tf.Tensor([ 9 10 11 13 14], shape=(5,), dtype=int32)
tf.Tensor([ 9 10 11 13 14], shape=(5,), dtype=int32)


In [29]:
x = tf.constant([1, 2], dtype=tf.dtypes.int8)   # dtype matters
y = [2**7 + 1, 2**7 + 2]
tf.add(x, y)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>

In [30]:
x_1 = tf.constant([1,2,3,4,5], dtype=tf.float32)  # shape -> (1,5)
x_2 = tf.constant([[3],[5],[7]], dtype=tf.float32) # shape -> (3,1)
print(tf.math.add(x_1, x_2)) # shape -> (3,5)

tf.Tensor(
[[ 4.  5.  6.  7.  8.]
 [ 6.  7.  8.  9. 10.]
 [ 8.  9. 10. 11. 12.]], shape=(3, 5), dtype=float32)


In [31]:
a = tf.constant([5,4,-3,-6,-2,4])
b = tf.constant([4,5,0,0,-1,0])
c = tf.constant([-3])
print(tf.math.minimum(a,b))
print(tf.math.minimum(a,c))
print(tf.math.maximum(a,b))

tf.Tensor([ 4  4 -3 -6 -2  0], shape=(6,), dtype=int32)
tf.Tensor([-3 -3 -3 -6 -3 -3], shape=(6,), dtype=int32)
tf.Tensor([ 5  5  0  0 -1  4], shape=(6,), dtype=int32)


In [32]:
# tf.math.argmax(
#     input,
#     axis=None,
#     output_type=tf.dtypes.int64,
#     name=None
# )
x_check = tf.constant([
    [4,2,3,1],
    [5,6,7,8],
    [9,10,1,12],
])
print(tf.math.argmax(x_check, axis=1))  # provide the index of the maximum element axis wise
                                    # axis=0 -> colomn (default)
                                    # axis=1 -> row
print(tf.math.argmin(x_check))

tf.Tensor([0 3 3], shape=(3,), dtype=int64)
tf.Tensor([0 0 2 0], shape=(4,), dtype=int64)


In [33]:
# tf.math.pow(
#     x, y, name=None
# )
tf.math.pow(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [34]:
# tf.math.reduce_sum(
#     input_tensor, axis=None, keepdims=False, name=None
# )
tensor_two_d = tf.constant([[2,3,4],
                            [5,6,7],
                            [9,4,2]], dtype = tf.float32)
# when it is none --> sum the whole matrix together
# when it is axis is 0 or 1 it returns the axis wise sum
print(tf.math.reduce_sum(
    tensor_two_d, axis=None, keepdims=False, name=None
))

print(tf.math.reduce_max(
    tensor_two_d, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_min(
    tensor_two_d, axis=None, keepdims=False, name=None
))
       # keepdims = True
print(tf.math.reduce_min(
    tensor_two_d, axis=None, keepdims=True, name=None
))

print(tf.math.reduce_mean(
    tensor_two_d, axis=0, keepdims=False, name=None
))

print(tf.math.reduce_prod(
    tensor_two_d, axis=None, keepdims=False, name=None
))

tf.Tensor(42.0, shape=(), dtype=float32)
tf.Tensor([4. 7. 9.], shape=(3,), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
tf.Tensor([5.3333335 4.3333335 4.3333335], shape=(3,), dtype=float32)
tf.Tensor(362880.0, shape=(), dtype=float32)


In [35]:
# tf.math.top_k(
#     input,
#     k=1,   k -> no of max value you need in each row
#     sorted=True,
#     index_type=tf.dtypes.int32,
#     name=None
# )

tensor_two_d = tf.constant([[2,3,4],
                            [5,6,7],
                            [9,4,2]], dtype = tf.float32)
print(tf.math.top_k(tensor_two_d, k=1))

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [7.],
       [9.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [0]], dtype=int32)>)


numpy=
array([[4.],
       [7.],
       [9.]]]
so these are the max values and below are there indices

numpy=array([[2],
             [2],
             [0]], dtype=int32)>)

In [36]:
# matrix multiplication

x_1 = tf.constant([[1,2,0],
                   [3,5,-1]])   # shape -> (2,3)
x_2 = tf.constant([[1,2,0,2],   # x_2 shape must start with 3,anything so shape -> (3,4)
                   [3,5,-1,0],
                   [3,2,4,5]])

print(tf.linalg.matmul(
    x_1, x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
))
# this matrix multiplication can also be done this way
print(x_1@x_2)

tf.Tensor(
[[ 7 12 -2  2]
 [15 29 -9  1]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 7 12 -2  2]
 [15 29 -9  1]], shape=(2, 4), dtype=int32)


In [37]:
# transpose of matrix
print(x_1)
print(tf.transpose(x_1))
print("\n",x_2)
print(tf.transpose(x_2))

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)

 tf.Tensor(
[[ 1  2  0  2]
 [ 3  5 -1  0]
 [ 3  2  4  5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 1  3  3]
 [ 2  5  2]
 [ 0 -1  4]
 [ 2  0  5]], shape=(4, 3), dtype=int32)


In [38]:
# this transpose thing can be directly done in matmul function ... there while you want to multiply the x_1 with transpose of x_3
x_1 = tf.constant([[1,2,0],
                   [3,5,-1]])   # shape -> (2,3) ->T ->(3,2)
x_3 = tf.constant([[1,2],   # x_3 shape must start with 3,anything so shape -> (3,2) ->T ->(2,3)
                   [3,5],
                   [3,2]])

print(tf.linalg.matmul(
    x_1, x_3,
    transpose_a=True,
    transpose_b=True,   # transpose of matrix x_2
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,   # if True then faster calculation done by it ... as mostly zero
    b_is_sparse=False,
    output_type=None,
    name=None
))
print(tf.transpose(x_1)@ tf.transpose(x_3))


tf.Tensor(
[[ 7 18  9]
 [12 31 16]
 [-2 -5 -2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 7 18  9]
 [12 31 16]
 [-2 -5 -2]], shape=(3, 3), dtype=int32)


In [39]:
tensor_two_d = tf.constant([[1,-2,0,3],
                            [3,5,100,5],
                            [1,5,6,-5],
                            [2,3,8,4]], dtype=tf.dtypes.float32
)
 # tf.linalg.band_part(input, 0, -1) ==> Upper triangular part.
 # tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
 # tf.linalg.band_part(input, 0, 0) ==> Diagonal.

print(tf.linalg.band_part(tensor_two_d, 0, 0))
print(tf.linalg.band_part(tensor_two_d, -1, 0))

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 4.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0.]
 [3. 5. 0. 0.]
 [1. 5. 6. 0.]
 [2. 3. 8. 4.]], shape=(4, 4), dtype=float32)


In [40]:
print(tf.linalg.inv(tensor_two_d))

tf.Tensor(
[[ 8.3333337e-01 -1.6829487e-02  4.0716609e-01 -9.5005497e-02]
 [-3.3333334e-01 -1.4115087e-02 -4.5602597e-02  2.1064061e-01]
 [ 1.1281635e-09  1.1400650e-02 -1.6286643e-03 -1.6286643e-02]
 [-1.6666666e-01 -3.8002189e-03 -1.6612376e-01  1.7209554e-01]], shape=(4, 4), dtype=float32)


In [42]:
# tf.einsum(
#     equation, *inputs, **kwargs
# )
x_1 = tf.constant([[1,2,0],
                   [3,5,-1]])
x_3 = tf.constant([[1,2],
                   [3,5],
                   [3,2]])
# tf.einsum("",tensor_two_d)