In [5]:
import tensorflow as tf
from tensorflow import keras

In [10]:
print("Hello world")

Hello world


In [11]:
import numpy

In [22]:
string = tf.Variable("This is a string", tf.string)
var = tf.Variable(139, tf.int16)
floating = tf.Variable(5.323, tf.float64)
rank1_tensor = tf.Variable(["Hello","Hii"], tf.string)
rank2_tensor = tf.Variable([["Hi","there"],["how you","doing"]], tf.string)


In [30]:
tf.rank(floating)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [28]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [32]:
rank2_tensor.shape

TensorShape([2, 2])

In [33]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3, -1])

In [35]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [40]:
tensor4 = tf.zeros([5,5,5,5])
# print(tensor4)
tensor4 = tf.reshape(tensor4, [125, -1])
print(tensor4)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]

In [44]:
matrix = [
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45]
]
print(matrix)
tf_matrix = tf.Variable(matrix, dtype = tf.int32)
print(tf_matrix)
print(tf.rank(tf_matrix))
print(tf_matrix.shape)

[[11, 12, 13, 14, 15], [21, 22, 23, 24, 25], [31, 32, 33, 34, 35], [41, 42, 43, 44, 45]]
<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [103]:
element1 = tf_matrix[0,0]
row1 = tf_matrix[0]
colomn1 = tf_matrix[:,0]
row2_and_4 = tf_matrix[0::2]
col1_in_row2_and_row_3 = tf_matrix[1:3,0]

print(element1)
print(row1)
print(colomn1)
print(row2_and_4)
print(col1_in_row2_and_row_3)

tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor([11 12 13 14 15], shape=(5,), dtype=int32)
tf.Tensor([11 21 31 41], shape=(4,), dtype=int32)
tf.Tensor(
[[11 12 13 14 15]
 [31 32 33 34 35]], shape=(2, 5), dtype=int32)
tf.Tensor([21 31], shape=(2,), dtype=int32)
